// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ecommerce.proto

package ecommerce_app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for OrderStatus
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_PROCESSING OrderStatus = 0 // Default value
	OrderStatus_ORDER_STATUS_COMPLETED  OrderStatus = 1
	OrderStatus_ORDER_STATUS_CANCELLED  OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_PROCESSING",
		1: "ORDER_STATUS_COMPLETED",
		2: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_PROCESSING": 0,
		"ORDER_STATUS_COMPLETED":  1,
		"ORDER_STATUS_CANCELLED":  2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ecommerce_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_ecommerce_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{0}
}

// Enum for PaymentStatus
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_PENDING   PaymentStatus = 0 // Default value
	PaymentStatus_PAYMENT_STATUS_COMPLETED PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_CANCELLED PaymentStatus = 2
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_PENDING",
		1: "PAYMENT_STATUS_COMPLETED",
		2: "PAYMENT_STATUS_CANCELLED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_PENDING":   0,
		"PAYMENT_STATUS_COMPLETED": 1,
		"PAYMENT_STATUS_CANCELLED": 2,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ecommerce_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_ecommerce_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{1}
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_ecommerce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Item          *CartItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_ecommerce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddItemRequest) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type EmptyCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyCartRequest) Reset() {
	*x = EmptyCartRequest{}
	mi := &file_ecommerce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyCartRequest) ProtoMessage() {}

func (x *EmptyCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyCartRequest.ProtoReflect.Descriptor instead.
func (*EmptyCartRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{2}
}

func (x *EmptyCartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_ecommerce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_ecommerce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{4}
}

func (x *Cart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_ecommerce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveItemRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoveItemRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateItemQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQuantityRequest) Reset() {
	*x = UpdateItemQuantityRequest{}
	mi := &file_ecommerce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityRequest) ProtoMessage() {}

func (x *UpdateItemQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemQuantityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateItemQuantityRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemQuantityRequest) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ecommerce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{7}
}

type Product struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price       float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Inventory   uint64                 `protobuf:"varint,4,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// @gotags: gorm:"type:varchar(255)[]"
	Images          []string `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty" gorm:"type:varchar(255)[]"` // [bucketname]
	StripePriceId   string   `protobuf:"bytes,7,opt,name=stripe_price_id,json=stripePriceId,proto3" json:"stripe_price_id,omitempty"`
	StripeProductId string   `protobuf:"bytes,8,opt,name=stripe_product_id,json=stripeProductId,proto3" json:"stripe_product_id,omitempty"`
	MerchantId      uint64   `protobuf:"varint,9,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_ecommerce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{8}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetInventory() uint64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetStripePriceId() string {
	if x != nil {
		return x.StripePriceId
	}
	return ""
}

func (x *Product) GetStripeProductId() string {
	if x != nil {
		return x.StripeProductId
	}
	return ""
}

func (x *Product) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type UpdateProductImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Id            uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductImagesRequest) Reset() {
	*x = UpdateProductImagesRequest{}
	mi := &file_ecommerce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductImagesRequest) ProtoMessage() {}

func (x *UpdateProductImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductImagesRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductImagesRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductImagesRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UpdateProductImagesRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UpdateProductImagesRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProductImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadedFiles []string               `protobuf:"bytes,1,rep,name=uploaded_files,json=uploadedFiles,proto3" json:"uploaded_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductImagesResponse) Reset() {
	*x = UpdateProductImagesResponse{}
	mi := &file_ecommerce_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductImagesResponse) ProtoMessage() {}

func (x *UpdateProductImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductImagesResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductImagesResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductImagesResponse) GetUploadedFiles() []string {
	if x != nil {
		return x.UploadedFiles
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Inventory     uint64                 `protobuf:"varint,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MerchantId    uint64                 `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_ecommerce_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{11}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetInventory() uint64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type UpdateProductRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price           float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Inventory       uint64                 `protobuf:"varint,4,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Images          []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	StripePriceId   string                 `protobuf:"bytes,7,opt,name=stripe_price_id,json=stripePriceId,proto3" json:"stripe_price_id,omitempty"`
	StripeProductId string                 `protobuf:"bytes,8,opt,name=stripe_product_id,json=stripeProductId,proto3" json:"stripe_product_id,omitempty"`
	MerchantId      uint64                 `protobuf:"varint,9,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_ecommerce_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetInventory() uint64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateProductRequest) GetStripePriceId() string {
	if x != nil {
		return x.StripePriceId
	}
	return ""
}

func (x *UpdateProductRequest) GetStripeProductId() string {
	if x != nil {
		return x.StripeProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    uint64                 `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_ecommerce_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteProductRequest) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_ecommerce_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{14}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListProductsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	MerchantId    uint64                 `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_ecommerce_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{15}
}

func (x *ListProductsRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_ecommerce_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{16}
}

func (x *GetProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ValidateProductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductInventoryRequest) Reset() {
	*x = ValidateProductInventoryRequest{}
	mi := &file_ecommerce_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductInventoryRequest) ProtoMessage() {}

func (x *ValidateProductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductInventoryRequest.ProtoReflect.Descriptor instead.
func (*ValidateProductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateProductInventoryRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ValidateProductInventoryRequest) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ValidateProductInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductInventoryResponse) Reset() {
	*x = ValidateProductInventoryResponse{}
	mi := &file_ecommerce_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductInventoryResponse) ProtoMessage() {}

func (x *ValidateProductInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductInventoryResponse.ProtoReflect.Descriptor instead.
func (*ValidateProductInventoryResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateProductInventoryResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_ecommerce_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{19}
}

func (x *PlaceOrderRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceOrderRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_ecommerce_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{20}
}

func (x *PlaceOrderResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_ecommerce_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{21}
}

func (x *OrderItem) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Total             float32                `protobuf:"fixed32,3,opt,name=total,proto3" json:"total,omitempty"`
	Status            OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=ecommerce.OrderStatus" json:"status,omitempty"`
	TransactionId     string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CheckoutSessionId string                 `protobuf:"bytes,6,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	PaymentStatus     PaymentStatus          `protobuf:"varint,7,opt,name=payment_status,json=paymentStatus,proto3,enum=ecommerce.PaymentStatus" json:"payment_status,omitempty"`
	OrderItems        []*OrderItem           `protobuf:"bytes,8,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_ecommerce_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{22}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_PROCESSING
}

func (x *Order) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Order) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

func (x *Order) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_PENDING
}

func (x *Order) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_ecommerce_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{23}
}

func (x *GetOrderRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrdersByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserRequest) Reset() {
	*x = GetOrdersByUserRequest{}
	mi := &file_ecommerce_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserRequest) ProtoMessage() {}

func (x *GetOrdersByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{24}
}

func (x *GetOrdersByUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrdersByMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    uint64                 `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByMerchantRequest) Reset() {
	*x = GetOrdersByMerchantRequest{}
	mi := &file_ecommerce_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByMerchantRequest) ProtoMessage() {}

func (x *GetOrdersByMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByMerchantRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{25}
}

func (x *GetOrdersByMerchantRequest) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_ecommerce_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{26}
}

func (x *GetOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_ecommerce_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateOrderStatusRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_ecommerce_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{28}
}

func (x *CancelOrderRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_ecommerce_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteOrderRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_ecommerce_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_proto_rawDescGZIP(), []int{30}
}

func (x *UpdatePaymentStatusRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_ecommerce_proto protoreflect.FileDescriptor

const file_ecommerce_proto_rawDesc = "" +
	"\n" +
	"\x0fecommerce.proto\x12\tecommerce\"6\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\"X\n" +
	"\x0eAddItemRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x04item\x18\x02 \x01(\v2\x13.ecommerce.CartItemR\x04item\"1\n" +
	"\x10EmptyCartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"/\n" +
	"\x0eGetCartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"P\n" +
	"\x04Cart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.ecommerce.CartItemR\x05items\"B\n" +
	"\x11RemoveItemRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"f\n" +
	"\x19UpdateItemQuantityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\"\a\n" +
	"\x05Empty\"\x90\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1c\n" +
	"\tinventory\x18\x04 \x01(\x04R\tinventory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12&\n" +
	"\x0fstripe_price_id\x18\a \x01(\tR\rstripePriceId\x12*\n" +
	"\x11stripe_product_id\x18\b \x01(\tR\x0fstripeProductId\x12\x1f\n" +
	"\vmerchant_id\x18\t \x01(\x04R\n" +
	"merchantId\"g\n" +
	"\x1aUpdateProductImagesRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\"D\n" +
	"\x1bUpdateProductImagesResponse\x12%\n" +
	"\x0euploaded_files\x18\x01 \x03(\tR\ruploadedFiles\"\xa1\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1c\n" +
	"\tinventory\x18\x03 \x01(\x04R\tinventory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x04R\n" +
	"merchantId\"\x9d\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1c\n" +
	"\tinventory\x18\x04 \x01(\x04R\tinventory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12&\n" +
	"\x0fstripe_price_id\x18\a \x01(\tR\rstripePriceId\x12*\n" +
	"\x11stripe_product_id\x18\b \x01(\tR\x0fstripeProductId\x12\x1f\n" +
	"\vmerchant_id\x18\t \x01(\x04R\n" +
	"merchantId\"G\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x04R\n" +
	"merchantId\"t\n" +
	"\x14ListProductsResponse\x12.\n" +
	"\bproducts\x18\x01 \x03(\v2\x12.ecommerce.ProductR\bproducts\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"d\n" +
	"\x13ListProductsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x04R\n" +
	"merchantId\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\\\n" +
	"\x1fValidateProductInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\"8\n" +
	" ValidateProductInventoryResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"j\n" +
	"\x11PlaceOrderRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\"7\n" +
	"\x12PlaceOrderResponse\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl\"\xb5\x01\n" +
	"\tOrderItem\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x83\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x02R\x05total\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.ecommerce.OrderStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12.\n" +
	"\x13checkout_session_id\x18\x06 \x01(\tR\x11checkoutSessionId\x12?\n" +
	"\x0epayment_status\x18\a \x01(\x0e2\x18.ecommerce.PaymentStatusR\rpaymentStatus\x125\n" +
	"\vorder_items\x18\b \x03(\v2\x14.ecommerce.OrderItemR\n" +
	"orderItems\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"1\n" +
	"\x16GetOrdersByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"=\n" +
	"\x1aGetOrdersByMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x04R\n" +
	"merchantId\"=\n" +
	"\x11GetOrdersResponse\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.ecommerce.OrderR\x06orders\"B\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"$\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"$\n" +
	"\x12DeleteOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"L\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x04R\aorderId*b\n" +
	"\vOrderStatus\x12\x1b\n" +
	"\x17ORDER_STATUS_PROCESSING\x10\x00\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x02*g\n" +
	"\rPaymentStatus\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x00\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x022\xce\x02\n" +
	"\vCartService\x128\n" +
	"\aAddItem\x12\x19.ecommerce.AddItemRequest\x1a\x10.ecommerce.Empty\"\x00\x127\n" +
	"\aGetCart\x12\x19.ecommerce.GetCartRequest\x1a\x0f.ecommerce.Cart\"\x00\x12<\n" +
	"\tEmptyCart\x12\x1b.ecommerce.EmptyCartRequest\x1a\x10.ecommerce.Empty\"\x00\x12>\n" +
	"\n" +
	"RemoveItem\x12\x1c.ecommerce.RemoveItemRequest\x1a\x10.ecommerce.Empty\"\x00\x12N\n" +
	"\x12UpdateItemQuantity\x12$.ecommerce.UpdateItemQuantityRequest\x1a\x10.ecommerce.Empty\"\x002\xa9\x05\n" +
	"\x0eProductService\x12Q\n" +
	"\fListProducts\x12\x1e.ecommerce.ListProductsRequest\x1a\x1f.ecommerce.ListProductsResponse\"\x00\x12@\n" +
	"\n" +
	"GetProduct\x12\x1c.ecommerce.GetProductRequest\x1a\x12.ecommerce.Product\"\x00\x12F\n" +
	"\rCreateProduct\x12\x1f.ecommerce.CreateProductRequest\x1a\x12.ecommerce.Product\"\x00\x12D\n" +
	"\rDeleteProduct\x12\x1f.ecommerce.DeleteProductRequest\x1a\x10.ecommerce.Empty\"\x00\x12F\n" +
	"\rUpdateProduct\x12\x1f.ecommerce.UpdateProductRequest\x1a\x12.ecommerce.Product\"\x00\x12h\n" +
	"\x13UpdateProductImages\x12%.ecommerce.UpdateProductImagesRequest\x1a&.ecommerce.UpdateProductImagesResponse\"\x00(\x01\x12u\n" +
	"\x18ValidateProductInventory\x12*.ecommerce.ValidateProductInventoryRequest\x1a+.ecommerce.ValidateProductInventoryResponse\"\x00\x12K\n" +
	"\n" +
	"PlaceOrder\x12\x1c.ecommerce.PlaceOrderRequest\x1a\x1d.ecommerce.PlaceOrderResponse\"\x002\xa2\x04\n" +
	"\fOrderService\x12:\n" +
	"\bGetOrder\x12\x1a.ecommerce.GetOrderRequest\x1a\x10.ecommerce.Order\"\x00\x12T\n" +
	"\x0fGetOrdersByUser\x12!.ecommerce.GetOrdersByUserRequest\x1a\x1c.ecommerce.GetOrdersResponse\"\x00\x12\\\n" +
	"\x13GetOrdersByMerchant\x12%.ecommerce.GetOrdersByMerchantRequest\x1a\x1c.ecommerce.GetOrdersResponse\"\x00\x12L\n" +
	"\x11UpdateOrderStatus\x12#.ecommerce.UpdateOrderStatusRequest\x1a\x10.ecommerce.Order\"\x00\x12@\n" +
	"\vCancelOrder\x12\x1d.ecommerce.CancelOrderRequest\x1a\x10.ecommerce.Order\"\x00\x12@\n" +
	"\vDeleteOrder\x12\x1d.ecommerce.DeleteOrderRequest\x1a\x10.ecommerce.Empty\"\x00\x12P\n" +
	"\x13UpdatePaymentStatus\x12%.ecommerce.UpdatePaymentStatusRequest\x1a\x10.ecommerce.Empty\"\x00B2Z0https://github.com/CS464-ECOMMERCE/ecommerce-appb\x06proto3"

var (
	file_ecommerce_proto_rawDescOnce sync.Once
	file_ecommerce_proto_rawDescData []byte
)

func file_ecommerce_proto_rawDescGZIP() []byte {
	file_ecommerce_proto_rawDescOnce.Do(func() {
		file_ecommerce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_proto_rawDesc), len(file_ecommerce_proto_rawDesc)))
	})
	return file_ecommerce_proto_rawDescData
}

var file_ecommerce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ecommerce_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_ecommerce_proto_goTypes = []any{
	(OrderStatus)(0),                         // 0: ecommerce.OrderStatus
	(PaymentStatus)(0),                       // 1: ecommerce.PaymentStatus
	(*CartItem)(nil),                         // 2: ecommerce.CartItem
	(*AddItemRequest)(nil),                   // 3: ecommerce.AddItemRequest
	(*EmptyCartRequest)(nil),                 // 4: ecommerce.EmptyCartRequest
	(*GetCartRequest)(nil),                   // 5: ecommerce.GetCartRequest
	(*Cart)(nil),                             // 6: ecommerce.Cart
	(*RemoveItemRequest)(nil),                // 7: ecommerce.RemoveItemRequest
	(*UpdateItemQuantityRequest)(nil),        // 8: ecommerce.UpdateItemQuantityRequest
	(*Empty)(nil),                            // 9: ecommerce.Empty
	(*Product)(nil),                          // 10: ecommerce.Product
	(*UpdateProductImagesRequest)(nil),       // 11: ecommerce.UpdateProductImagesRequest
	(*UpdateProductImagesResponse)(nil),      // 12: ecommerce.UpdateProductImagesResponse
	(*CreateProductRequest)(nil),             // 13: ecommerce.CreateProductRequest
	(*UpdateProductRequest)(nil),             // 14: ecommerce.UpdateProductRequest
	(*DeleteProductRequest)(nil),             // 15: ecommerce.DeleteProductRequest
	(*ListProductsResponse)(nil),             // 16: ecommerce.ListProductsResponse
	(*ListProductsRequest)(nil),              // 17: ecommerce.ListProductsRequest
	(*GetProductRequest)(nil),                // 18: ecommerce.GetProductRequest
	(*ValidateProductInventoryRequest)(nil),  // 19: ecommerce.ValidateProductInventoryRequest
	(*ValidateProductInventoryResponse)(nil), // 20: ecommerce.ValidateProductInventoryResponse
	(*PlaceOrderRequest)(nil),                // 21: ecommerce.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),               // 22: ecommerce.PlaceOrderResponse
	(*OrderItem)(nil),                        // 23: ecommerce.OrderItem
	(*Order)(nil),                            // 24: ecommerce.Order
	(*GetOrderRequest)(nil),                  // 25: ecommerce.GetOrderRequest
	(*GetOrdersByUserRequest)(nil),           // 26: ecommerce.GetOrdersByUserRequest
	(*GetOrdersByMerchantRequest)(nil),       // 27: ecommerce.GetOrdersByMerchantRequest
	(*GetOrdersResponse)(nil),                // 28: ecommerce.GetOrdersResponse
	(*UpdateOrderStatusRequest)(nil),         // 29: ecommerce.UpdateOrderStatusRequest
	(*CancelOrderRequest)(nil),               // 30: ecommerce.CancelOrderRequest
	(*DeleteOrderRequest)(nil),               // 31: ecommerce.DeleteOrderRequest
	(*UpdatePaymentStatusRequest)(nil),       // 32: ecommerce.UpdatePaymentStatusRequest
}
var file_ecommerce_proto_depIdxs = []int32{
	2,  // 0: ecommerce.AddItemRequest.item:type_name -> ecommerce.CartItem
	2,  // 1: ecommerce.Cart.items:type_name -> ecommerce.CartItem
	10, // 2: ecommerce.ListProductsResponse.products:type_name -> ecommerce.Product
	0,  // 3: ecommerce.Order.status:type_name -> ecommerce.OrderStatus
	1,  // 4: ecommerce.Order.payment_status:type_name -> ecommerce.PaymentStatus
	23, // 5: ecommerce.Order.order_items:type_name -> ecommerce.OrderItem
	24, // 6: ecommerce.GetOrdersResponse.orders:type_name -> ecommerce.Order
	3,  // 7: ecommerce.CartService.AddItem:input_type -> ecommerce.AddItemRequest
	5,  // 8: ecommerce.CartService.GetCart:input_type -> ecommerce.GetCartRequest
	4,  // 9: ecommerce.CartService.EmptyCart:input_type -> ecommerce.EmptyCartRequest
	7,  // 10: ecommerce.CartService.RemoveItem:input_type -> ecommerce.RemoveItemRequest
	8,  // 11: ecommerce.CartService.UpdateItemQuantity:input_type -> ecommerce.UpdateItemQuantityRequest
	17, // 12: ecommerce.ProductService.ListProducts:input_type -> ecommerce.ListProductsRequest
	18, // 13: ecommerce.ProductService.GetProduct:input_type -> ecommerce.GetProductRequest
	13, // 14: ecommerce.ProductService.CreateProduct:input_type -> ecommerce.CreateProductRequest
	15, // 15: ecommerce.ProductService.DeleteProduct:input_type -> ecommerce.DeleteProductRequest
	14, // 16: ecommerce.ProductService.UpdateProduct:input_type -> ecommerce.UpdateProductRequest
	11, // 17: ecommerce.ProductService.UpdateProductImages:input_type -> ecommerce.UpdateProductImagesRequest
	19, // 18: ecommerce.ProductService.ValidateProductInventory:input_type -> ecommerce.ValidateProductInventoryRequest
	21, // 19: ecommerce.ProductService.PlaceOrder:input_type -> ecommerce.PlaceOrderRequest
	25, // 20: ecommerce.OrderService.GetOrder:input_type -> ecommerce.GetOrderRequest
	26, // 21: ecommerce.OrderService.GetOrdersByUser:input_type -> ecommerce.GetOrdersByUserRequest
	27, // 22: ecommerce.OrderService.GetOrdersByMerchant:input_type -> ecommerce.GetOrdersByMerchantRequest
	29, // 23: ecommerce.OrderService.UpdateOrderStatus:input_type -> ecommerce.UpdateOrderStatusRequest
	30, // 24: ecommerce.OrderService.CancelOrder:input_type -> ecommerce.CancelOrderRequest
	31, // 25: ecommerce.OrderService.DeleteOrder:input_type -> ecommerce.DeleteOrderRequest
	32, // 26: ecommerce.OrderService.UpdatePaymentStatus:input_type -> ecommerce.UpdatePaymentStatusRequest
	9,  // 27: ecommerce.CartService.AddItem:output_type -> ecommerce.Empty
	6,  // 28: ecommerce.CartService.GetCart:output_type -> ecommerce.Cart
	9,  // 29: ecommerce.CartService.EmptyCart:output_type -> ecommerce.Empty
	9,  // 30: ecommerce.CartService.RemoveItem:output_type -> ecommerce.Empty
	9,  // 31: ecommerce.CartService.UpdateItemQuantity:output_type -> ecommerce.Empty
	16, // 32: ecommerce.ProductService.ListProducts:output_type -> ecommerce.ListProductsResponse
	10, // 33: ecommerce.ProductService.GetProduct:output_type -> ecommerce.Product
	10, // 34: ecommerce.ProductService.CreateProduct:output_type -> ecommerce.Product
	9,  // 35: ecommerce.ProductService.DeleteProduct:output_type -> ecommerce.Empty
	10, // 36: ecommerce.ProductService.UpdateProduct:output_type -> ecommerce.Product
	12, // 37: ecommerce.ProductService.UpdateProductImages:output_type -> ecommerce.UpdateProductImagesResponse
	20, // 38: ecommerce.ProductService.ValidateProductInventory:output_type -> ecommerce.ValidateProductInventoryResponse
	22, // 39: ecommerce.ProductService.PlaceOrder:output_type -> ecommerce.PlaceOrderResponse
	24, // 40: ecommerce.OrderService.GetOrder:output_type -> ecommerce.Order
	28, // 41: ecommerce.OrderService.GetOrdersByUser:output_type -> ecommerce.GetOrdersResponse
	28, // 42: ecommerce.OrderService.GetOrdersByMerchant:output_type -> ecommerce.GetOrdersResponse
	24, // 43: ecommerce.OrderService.UpdateOrderStatus:output_type -> ecommerce.Order
	24, // 44: ecommerce.OrderService.CancelOrder:output_type -> ecommerce.Order
	9,  // 45: ecommerce.OrderService.DeleteOrder:output_type -> ecommerce.Empty
	9,  // 46: ecommerce.OrderService.UpdatePaymentStatus:output_type -> ecommerce.Empty
	27, // [27:47] is the sub-list for method output_type
	7,  // [7:27] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ecommerce_proto_init() }
func file_ecommerce_proto_init() {
	if File_ecommerce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_proto_rawDesc), len(file_ecommerce_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_ecommerce_proto_goTypes,
		DependencyIndexes: file_ecommerce_proto_depIdxs,
		EnumInfos:         file_ecommerce_proto_enumTypes,
		MessageInfos:      file_ecommerce_proto_msgTypes,
	}.Build()
	File_ecommerce_proto = out.File
	file_ecommerce_proto_goTypes = nil
	file_ecommerce_proto_depIdxs = nil
}
